### ISSUE TITLE
Avoid long exception messages

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/galitime#33]
Example:

```bash
$ ./galitime.py  -r 5 sleep
usage: sleep seconds
Traceback (most recent call last):
  File "/Users/karel/git/_MOF_/galitime/./galitime.py", line 347, in <module>
    main()
  File "/Users/karel/git/_MOF_/galitime/./galitime.py", line 340, in main
    run_timing(
  File "/Users/karel/git/_MOF_/galitime/./galitime.py", line 250, in run_timing
    t.run(times=repetitions)
  File "/Users/karel/git/_MOF_/galitime/./galitime.py", line 107, in run
    self._execute_time()
  File "/Users/karel/git/_MOF_/galitime/./galitime.py", line 135, in _execute_time
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '/usr/bin/env time -o /var/folders/z6/8lsjsl3x5q94j7041rtdwqyh0000gq/T/tmplqy62dbg/timing_output.run_1.log -l -p sleep' returned non-zero exit status 1.

**Comment by karel-brinda** [comment]
Fixed by #36
