### ISSUE TITLE
Error messages are not intuitive

### ISSUE THREAD

**Issue by Francii-B** [karel-brinda/galitime#38]
Example error message:

```
time: cannot run fulgor: No such file or directory
Traceback (most recent call last):
  File "/home/injera/miniconda3/envs/utilities/bin/galitime", line 10, in <module>
	sys.exit(main())
  File "/home/injera/miniconda3/envs/utilities/lib/python3.10/site-packages/galitime/galitime.py", line 334, in main
	run_timing(
  File "/home/injera/miniconda3/envs/utilities/lib/python3.10/site-packages/galitime/galitime.py", line 249, in run_timing
	t.run()
  File "/home/injera/miniconda3/envs/utilities/lib/python3.10/site-packages/galitime/galitime.py", line 106, in run
	self._execute_time()
  File "/home/injera/miniconda3/envs/utilities/lib/python3.10/site-packages/galitime/galitime.py", line 134, in _execute_time
	raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '/usr/bin/env time -o /tmp/tmpgp0qwdc5/timing_output.run_1.log -f "%e	%U	%S	%P	%M	%x	%I	%O" fulgor stats -i prova.mfur' returned non-zero exit status 127.
```
The error was written above the traceback, which is counter-intuitive for users

**Comment by karel-brinda** [comment]
Already fixed by:
* https://github.com/karel-brinda/galitime/commit/6106b50 – Implement proper error propagation
* https://github.com/karel-brinda/galitime/commit/6bb0f52 – Fix canonical exit-code handling for timed commands

In short, it no longer prints the annoying Python tracebacks.
